-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 13:28:33 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema posdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema posdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `posdb` ;

-- -----------------------------------------------------
-- Table `posdb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posdb`.`User` ;

CREATE TABLE IF NOT EXISTS `posdb`.`User` (
  `ID` VARCHAR(20) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Berechtigungen` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posdb`.`Funktion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posdb`.`Funktion` ;

CREATE TABLE IF NOT EXISTS `posdb`.`Funktion` (
  `ID` VARCHAR(20) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
