-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 13:49:14 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema klassensparbuchdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema klassensparbuchdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `klassensparbuchdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `klassensparbuchdb` ;

-- -----------------------------------------------------
-- Table `klassensparbuchdb`.`Konto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klassensparbuchdb`.`Konto` (
  `idKonto` INT NOT NULL,
  `Kontostand` DOUBLE NOT NULL,
  PRIMARY KEY (`idKonto`),
  UNIQUE INDEX `idKonto_UNIQUE` (`idKonto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `klassensparbuchdb`.`Nutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `klassensparbuchdb`.`Nutzer` (
  `Name` VARCHAR(50) NOT NULL,
  `ID` VARCHAR(5) NOT NULL,
  `PW` VARCHAR(100) NOT NULL,
  `idKonto` INT NULL,
  PRIMARY KEY (`ID`, `idKonto`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_Nutzer_Konto_idx` (`idKonto` ASC),
  CONSTRAINT `fk_Nutzer_Konto`
    FOREIGN KEY (`idKonto`)
    REFERENCES `klassensparbuchdb`.`Konto` (`idKonto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
